/**
 * REFILL ALERTS COMPONENT
 * Displays medication refill reminders for elderly users
 * Medical-grade inventory management
 */

import { useState, useEffect } from 'react';
import { AlertCircle, Phone, Printer, Download, Clock, Package } from 'lucide-react';
import { Button } from './ui/button';
import { Card } from './ui/card';
import {
  MedicationInventory,
  RefillAlert,
  checkAllRefills,
  getUrgencyColor,
  formatRunOutDate,
  exportRefillAlertsAsText,
} from '../utils/refillReminders';

interface RefillAlertsProps {
  medications: any[];
  darkMode: boolean;
}

export default function RefillAlerts({ medications, darkMode }: RefillAlertsProps) {
  const [alerts, setAlerts] = useState<RefillAlert[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Convert medications to inventory format
    const inventories: MedicationInventory[] = medications.map((med) => ({
      medicationId: med.id,
      medicationName: med.name,
      totalQuantity: 90, // Assume 90-day supply
      quantityRemaining: Math.floor(Math.random() * 90), // Demo: random remaining
      quantityPerDose: parseFloat(med.quantity) || 1,
      dosesPerDay: med.timesPerDay || 1,
      lastRefillDate: med.startDate,
      prescriptionNumber: `RX${med.id}`,
      pharmacyName: 'CVS Pharmacy',
      pharmacyPhone: '1-800-746-7287',
      autoRefill: false,
    }));

    // Check for refills needed
    const refillAlerts = checkAllRefills(inventories);
    setAlerts(refillAlerts);
    setLoading(false);
  }, [medications]);

  const handleExport = () => {
    const text = exportRefillAlertsAsText(alerts);
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `refill-alerts-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Medication Refill Alerts</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px 20px;
      font-size: 18px;
      line-height: 1.6;
    }
    .header {
      text-align: center;
      margin-bottom: 40px;
      border-bottom: 3px solid #2196F3;
      padding-bottom: 20px;
    }
    .alert {
      margin-bottom: 30px;
      padding: 20px;
      border: 3px solid #e2e8f0;
      border-radius: 12px;
      page-break-inside: avoid;
    }
    .critical {
      border-color: #ef4444;
      background: #fef2f2;
    }
    .urgent {
      border-color: #f97316;
      background: #fff7ed;
    }
    .soon {
      border-color: #eab308;
      background: #fefce8;
    }
    .medication-name {
      font-size: 24px;
      font-weight: bold;
      margin-bottom: 10px;
    }
    .detail {
      margin: 8px 0;
      padding-left: 20px;
    }
    .action {
      margin-top: 15px;
      padding: 15px;
      background: #f8fafc;
      border-radius: 8px;
      font-weight: 600;
    }
    @media print {
      body {
        padding: 20px;
      }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>Medication Refill Alerts</h1>
    <p>Generated: ${new Date().toLocaleDateString()}</p>
  </div>
  
  ${alerts
    .map(
      (alert) => `
    <div class="alert ${alert.urgency}">
      <div class="medication-name">${alert.medicationName}</div>
      <div class="detail"><strong>Status:</strong> ${alert.urgency.toUpperCase()}</div>
      <div class="detail"><strong>Days Remaining:</strong> ${alert.daysRemaining}</div>
      <div class="detail"><strong>Runs Out:</strong> ${formatRunOutDate(alert.estimatedRunOutDate)}</div>
      ${alert.prescriptionNumber ? `<div class="detail"><strong>Rx #:</strong> ${alert.prescriptionNumber}</div>` : ''}
      ${alert.pharmacyName ? `<div class="detail"><strong>Pharmacy:</strong> ${alert.pharmacyName}</div>` : ''}
      ${alert.pharmacyPhone ? `<div class="detail"><strong>Phone:</strong> ${alert.pharmacyPhone}</div>` : ''}
      <div class="action">
        <strong>Action Required:</strong><br/>
        ${alert.actionRequired}
      </div>
    </div>
  `
    )
    .join('')}
    
  <div style="text-align: center; margin-top: 40px; color: #64748b; font-size: 14px;">
    <p>Generated by Prescription Clarity</p>
    <p>This report is for informational purposes only.</p>
  </div>
</body>
</html>
    `;

    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.focus();
    printWindow.print();
  };

  if (loading) {
    return (
      <div className={`rounded-xl p-6 border-2 ${darkMode ? 'bg-gray-800 border-gray-700' : 'bg-white border-gray-200'}`}>
        <div className="flex items-center gap-3">
          <Package className={`w-6 h-6 animate-pulse ${darkMode ? 'text-gray-400' : 'text-gray-500'}`} />
          <span className={darkMode ? 'text-gray-300' : 'text-gray-700'}>Checking refill status...</span>
        </div>
      </div>
    );
  }

  if (alerts.length === 0) {
    return (
      <div className={`rounded-xl p-6 border-2 ${darkMode ? 'bg-gray-800 border-gray-700' : 'bg-white border-gray-200'}`}>
        <div className="flex items-center gap-3">
          <Package className={`w-6 h-6 ${darkMode ? 'text-green-400' : 'text-green-600'}`} />
          <div>
            <h3 className={`font-bold ${darkMode ? 'text-green-400' : 'text-green-600'}`}>
              All Medications Stocked
            </h3>
            <p className={`text-sm ${darkMode ? 'text-gray-400' : 'text-gray-600'}`}>
              No refills needed at this time
            </p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      {/* Header with Actions */}
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div className="flex items-center gap-3">
          <Package className={`w-7 h-7 ${darkMode ? 'text-orange-400' : 'text-orange-600'}`} />
          <div>
            <h2 className={`text-xl font-bold ${darkMode ? 'text-white' : 'text-gray-900'}`}>
              Refill Alerts
            </h2>
            <p className={`text-sm ${darkMode ? 'text-gray-400' : 'text-gray-600'}`}>
              {alerts.length} medication{alerts.length !== 1 ? 's' : ''} need attention
            </p>
          </div>
        </div>

        <div className="flex gap-2">
          <Button
            onClick={handlePrint}
            variant="outline"
            className={`h-12 px-4 ${darkMode ? 'border-gray-600 text-gray-300 hover:bg-gray-700' : ''}`}
          >
            <Printer className="w-5 h-5 mr-2" />
            Print
          </Button>
          <Button
            onClick={handleExport}
            variant="outline"
            className={`h-12 px-4 ${darkMode ? 'border-gray-600 text-gray-300 hover:bg-gray-700' : ''}`}
          >
            <Download className="w-5 h-5 mr-2" />
            Export
          </Button>
        </div>
      </div>

      {/* Alerts List */}
      <div className="space-y-3">
        {alerts.map((alert) => {
          const colors = getUrgencyColor(alert.urgency);
          return (
            <Card
              key={alert.medicationId}
              className={`p-5 border-3 ${colors.bg} ${colors.border}`}
            >
              <div className="flex items-start justify-between gap-4">
                <div className="flex-1">
                  {/* Medication Name */}
                  <div className="flex items-center gap-2 mb-2">
                    <AlertCircle className={`w-6 h-6 ${colors.text}`} />
                    <h3 className={`text-xl font-bold ${colors.text}`}>
                      {alert.medicationName}
                    </h3>
                  </div>

                  {/* Status Badge */}
                  <div className="flex items-center gap-2 mb-3">
                    <span className={`px-3 py-1 rounded-full text-sm font-bold ${colors.bg} ${colors.text} border-2 ${colors.border}`}>
                      {alert.urgency.toUpperCase()}
                    </span>
                    <span className={`text-base ${colors.text}`}>
                      {alert.daysRemaining} day{alert.daysRemaining !== 1 ? 's' : ''} remaining
                    </span>
                  </div>

                  {/* Details */}
                  <div className={`space-y-2 text-base ${darkMode ? 'text-gray-300' : 'text-gray-700'}`}>
                    <div className="flex items-center gap-2">
                      <Clock className="w-4 h-4" />
                      <span>
                        Runs out: <strong>{formatRunOutDate(alert.estimatedRunOutDate)}</strong>
                      </span>
                    </div>

                    <div className="flex items-center gap-2">
                      <Package className="w-4 h-4" />
                      <span>
                        Remaining: <strong>{alert.quantityRemaining} doses</strong>
                      </span>
                    </div>

                    {alert.prescriptionNumber && (
                      <div>
                        Rx #: <strong>{alert.prescriptionNumber}</strong>
                      </div>
                    )}

                    {alert.pharmacyName && (
                      <div className="flex items-center gap-2">
                        <span>
                          Pharmacy: <strong>{alert.pharmacyName}</strong>
                        </span>
                        {alert.pharmacyPhone && (
                          <a
                            href={`tel:${alert.pharmacyPhone}`}
                            className={`inline-flex items-center gap-1 px-2 py-1 rounded text-sm hover:underline ${darkMode ? 'bg-gray-700 text-blue-400' : 'bg-blue-50 text-blue-600'}`}
                          >
                            <Phone className="w-3 h-3" />
                            {alert.pharmacyPhone}
                          </a>
                        )}
                      </div>
                    )}
                  </div>

                  {/* Action Required */}
                  <div className={`mt-4 p-4 rounded-lg ${darkMode ? 'bg-gray-700/50' : 'bg-white/80'}`}>
                    <p className={`font-bold text-base ${colors.text}`}>
                      Action Required:
                    </p>
                    <p className={`mt-1 ${darkMode ? 'text-gray-300' : 'text-gray-700'}`}>
                      {alert.actionRequired}
                    </p>
                  </div>
                </div>

                {/* Call to Action Button */}
                {alert.pharmacyPhone && alert.urgency === 'critical' && (
                  <a
                    href={`tel:${alert.pharmacyPhone}`}
                    className="h-14 px-6 rounded-lg bg-red-600 hover:bg-red-700 text-white font-bold flex items-center gap-2 touch-manipulation transition-colors"
                  >
                    <Phone className="w-5 h-5" />
                    Call Now
                  </a>
                )}
              </div>
            </Card>
          );
        })}
      </div>
    </div>
  );
}
